name: Compile and Create PDF file
on:
  push:
  
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Have a local copy of the repository
        uses: actions/checkout@v4.2.2
      - name: Install .NET in runner
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Instalar dependencias
        run: dotnet restore
      - name: Compilar
        run: dotnet build --no-restore      
  crete-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
  
